export const bibliaRV1960 = [
    { nombre: "Genesis", archivo: "genesis.json" },
    { nombre: "Exodo", archivo: "exodo.json" },
    { nombre: "Levitico", archivo: "levitico.json" },
    { nombre: "Numeros", archivo: "numeros.json" },
    { nombre: "Deuteronomio", archivo: "deuteronomio.json" },
    { nombre: "Josue", archivo: "josue.json" },
    { nombre: "Jueces", archivo: "jueces.json" },
    { nombre: "Rut", archivo: "rut.json" },
    { nombre: "1 Samuel", archivo: "1_samuel.json" },
    { nombre: "2 Samuel", archivo: "2_samuel.json" },
    { nombre: "1 Reyes", archivo: "1_reyes.json" },
    { nombre: "2 Reyes", archivo: "2_reyes.json" },
    { nombre: "1 Cronicas", archivo: "1_cronicas.json" },
    { nombre: "2 Cronicas", archivo: "2_cronicas.json" },
    { nombre: "Esdras", archivo: "esdras.json" },
    { nombre: "Nehemias", archivo: "nehemias.json" },
    { nombre: "Ester", archivo: "ester.json" },
    { nombre: "Job", archivo: "job.json" },
    { nombre: "Salmos", archivo: "salmos.json" },
    { nombre: "Proverbios", archivo: "proverbios.json" },
    { nombre: "Eclesiastes", archivo: "eclesiastes.json" },
    { nombre: "Cantares", archivo: "cantares.json" },
    { nombre: "Isaias", archivo: "isaias.json" },
    { nombre: "Jeremias", archivo: "jeremias.json" },
    { nombre: "Lamentaciones", archivo: "lamentaciones.json" },
    { nombre: "Ezequiel", archivo: "ezequiel.json" },
    { nombre: "Daniel", archivo: "daniel.json" },
    { nombre: "Oseas", archivo: "oseas.json" },
    { nombre: "Joel", archivo: "joel.json" },
    { nombre: "Amos", archivo: "amos.json" },
    { nombre: "Abdias", archivo: "abdias.json" },
    { nombre: "Jonas", archivo: "jonas.json" },
    { nombre: "Miqueas", archivo: "miqueas.json" },
    { nombre: "Nahum", archivo: "nahum.json" },
    { nombre: "Habacuc", archivo: "habacuc.json" },
    { nombre: "Sofonias", archivo: "sofonias.json" },
    { nombre: "Hageo", archivo: "hageo.json" },
    { nombre: "Zacarias", archivo: "zacarias.json" },
    { nombre: "Malaquias", archivo: "malaquias.json" },
    { nombre: "Mateo", archivo: "mateo.json" },
    { nombre: "Marcos", archivo: "marcos.json" },
    { nombre: "Lucas", archivo: "lucas.json" },
    { nombre: "Juan", archivo: "juan.json" },
    { nombre: "Hechos", archivo: "hechos.json" },
    { nombre: "Romanos", archivo: "romanos.json" },
    { nombre: "1 Corintios", archivo: "1_corintios.json" },
    { nombre: "2 Corintios", archivo: "2_corintios.json" },
    { nombre: "Galatas", archivo: "galatas.json" },
    { nombre: "Efesios", archivo: "efesios.json" },
    { nombre: "Filipenses", archivo: "filipenses.json" },
    { nombre: "Colosenses", archivo: "colosenses.json" },
    { nombre: "1 Tesalonicenses", archivo: "1_tesalonicenses.json" },
    { nombre: "2 Tesalonicenses", archivo: "2_tesalonicenses.json" },
    { nombre: "1 Timoteo", archivo: "1_timoteo.json" },
    { nombre: "2 Timoteo", archivo: "2_timoteo.json" },
    { nombre: "Tito", archivo: "tito.json" },
    { nombre: "Filemon", archivo: "filemon.json" },
    { nombre: "Hebreos", archivo: "hebreos.json" },
    { nombre: "Santiago", archivo: "santiago.json" },
    { nombre: "1 Pedro", archivo: "1_pedro.json" },
    { nombre: "2 Pedro", archivo: "2_pedro.json" },
    { nombre: "1 Juan", archivo: "1_juan.json" },
    { nombre: "2 Juan", archivo: "2_juan.json" },
    { nombre: "3 Juan", archivo: "3_juan.json" },
    { nombre: "Judas", archivo: "judas.json" },
    { nombre: "Apocalipsis", archivo: "apocalipsis.json" }
  ];
  