// constants\bibliaRV1960.ts
export const bibliaRV1960 = [
  { nombre: "Genesis", archivo: "genesis.json", testamento: "Viejo" },
  { nombre: "Exodo", archivo: "exodo.json", testamento: "Viejo" },
  { nombre: "Levitico", archivo: "levitico.json", testamento: "Viejo" },
  { nombre: "Numeros", archivo: "numeros.json", testamento: "Viejo" },
  { nombre: "Deuteronomio", archivo: "deuteronomio.json", testamento: "Viejo" },
  { nombre: "Josue", archivo: "josue.json", testamento: "Viejo" },
  { nombre: "Jueces", archivo: "jueces.json", testamento: "Viejo" },
  { nombre: "Rut", archivo: "rut.json", testamento: "Viejo" },
  { nombre: "1 Samuel", archivo: "1_samuel.json", testamento: "Viejo" },
  { nombre: "2 Samuel", archivo: "2_samuel.json", testamento: "Viejo" },
  { nombre: "1 Reyes", archivo: "1_reyes.json", testamento: "Viejo" },
  { nombre: "2 Reyes", archivo: "2_reyes.json", testamento: "Viejo" },
  { nombre: "1 Cronicas", archivo: "1_cronicas.json", testamento: "Viejo" },
  { nombre: "2 Cronicas", archivo: "2_cronicas.json", testamento: "Viejo" },
  { nombre: "Esdras", archivo: "esdras.json", testamento: "Viejo" },
  { nombre: "Nehemias", archivo: "nehemias.json", testamento: "Viejo" },
  { nombre: "Ester", archivo: "ester.json", testamento: "Viejo" },
  { nombre: "Job", archivo: "job.json", testamento: "Viejo" },
  { nombre: "Salmos", archivo: "salmos.json", testamento: "Viejo" },
  { nombre: "Proverbios", archivo: "proverbios.json", testamento: "Viejo" },
  { nombre: "Eclesiastes", archivo: "eclesiastes.json", testamento: "Viejo" },
  { nombre: "Cantares", archivo: "cantares.json", testamento: "Viejo" },
  { nombre: "Isaias", archivo: "isaias.json", testamento: "Viejo" },
  { nombre: "Jeremias", archivo: "jeremias.json", testamento: "Viejo" },
  { nombre: "Lamentaciones", archivo: "lamentaciones.json", testamento: "Viejo" },
  { nombre: "Ezequiel", archivo: "ezequiel.json", testamento: "Viejo" },
  { nombre: "Daniel", archivo: "daniel.json", testamento: "Viejo" },
  { nombre: "Oseas", archivo: "oseas.json", testamento: "Viejo" },
  { nombre: "Joel", archivo: "joel.json", testamento: "Viejo" },
  { nombre: "Amos", archivo: "amos.json", testamento: "Viejo" },
  { nombre: "Abdias", archivo: "abdias.json", testamento: "Viejo" },
  { nombre: "Jonas", archivo: "jonas.json", testamento: "Viejo" },
  { nombre: "Miqueas", archivo: "miqueas.json", testamento: "Viejo" },
  { nombre: "Nahum", archivo: "nahum.json", testamento: "Viejo" },
  { nombre: "Habacuc", archivo: "habacuc.json", testamento: "Viejo" },
  { nombre: "Sofonias", archivo: "sofonias.json", testamento: "Viejo" },
  { nombre: "Hageo", archivo: "hageo.json", testamento: "Viejo" },
  { nombre: "Zacarias", archivo: "zacarias.json", testamento: "Viejo" },
  { nombre: "Malaquias", archivo: "malaquias.json", testamento: "Viejo" },
  { nombre: "Mateo", archivo: "mateo.json", testamento: "Nuevo" },
  { nombre: "Marcos", archivo: "marcos.json", testamento: "Nuevo" },
  { nombre: "Lucas", archivo: "lucas.json", testamento: "Nuevo" },
  { nombre: "Juan", archivo: "juan.json", testamento: "Nuevo" },
  { nombre: "Hechos", archivo: "hechos.json", testamento: "Nuevo" },
  { nombre: "Romanos", archivo: "romanos.json", testamento: "Nuevo" },
  { nombre: "1 Corintios", archivo: "1_corintios.json", testamento: "Nuevo" },
  { nombre: "2 Corintios", archivo: "2_corintios.json", testamento: "Nuevo" },
  { nombre: "Galatas", archivo: "galatas.json", testamento: "Nuevo" },
  { nombre: "Efesios", archivo: "efesios.json", testamento: "Nuevo" },
  { nombre: "Filipenses", archivo: "filipenses.json", testamento: "Nuevo" },
  { nombre: "Colosenses", archivo: "colosenses.json", testamento: "Nuevo" },
  { nombre: "1 Tesalonicenses", archivo: "1_tesalonicenses.json", testamento: "Nuevo" },
  { nombre: "2 Tesalonicenses", archivo: "2_tesalonicenses.json", testamento: "Nuevo" },
  { nombre: "1 Timoteo", archivo: "1_timoteo.json", testamento: "Nuevo" },
  { nombre: "2 Timoteo", archivo: "2_timoteo.json", testamento: "Nuevo" },
  { nombre: "Tito", archivo: "tito.json", testamento: "Nuevo" },
  { nombre: "Filemon", archivo: "filemon.json", testamento: "Nuevo" },
  { nombre: "Hebreos", archivo: "hebreos.json", testamento: "Nuevo" },
  { nombre: "Santiago", archivo: "santiago.json", testamento: "Nuevo" },
  { nombre: "1 Pedro", archivo: "1_pedro.json", testamento: "Nuevo" },
  { nombre: "2 Pedro", archivo: "2_pedro.json", testamento: "Nuevo" },
  { nombre: "1 Juan", archivo: "1_juan.json", testamento: "Nuevo" },
  { nombre: "2 Juan", archivo: "2_juan.json", testamento: "Nuevo" },
  { nombre: "3 Juan", archivo: "3_juan.json", testamento: "Nuevo" },
  { nombre: "Judas", archivo: "judas.json", testamento: "Nuevo" },
  { nombre: "Apocalipsis", archivo: "apocalipsis.json", testamento: "Nuevo" }
];
